In [146]:
path = "./data/house_prices.csv"

In [147]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns

In [148]:
df = pd.read_csv(path)

## Exploracion

In [149]:
df.head(3)

,Index,Title,Description,Amount(in rupees),Price (in rupees),location,Carpet Area,Status,Floor,Transaction,...,facing,overlooking,Society,Bathroom,Balcony,Car Parking,Ownership,Super Area,Dimensions,Plot Area
0,0,1 BHK Ready to Occupy Flat for sale in Srushti...,"Bhiwandi, Thane has an attractive 1 BHK Flat f...",42 Lac,6000.0,thane,500 sqft,Ready to Move,10 out of 11,Resale,...,NaN,NaN,Srushti Siddhi Mangal Murti Complex,1,2,NaN,NaN,NaN,NaN,NaN
1,1,2 BHK Ready to Occupy Flat for sale in Dosti V...,One can find this stunning 2 BHK flat for sale...,98 Lac,13799.0,thane,473 sqft,Ready to Move,3 out of 22,Resale,...,East,Garden/Park,Dosti Vihar,2,NaN,1 Open,Freehold,NaN,NaN,NaN
2,2,2 BHK Ready to Occupy Flat for sale in Sunrise...,Up for immediate sale is a 2 BHK apartment in ...,1.40 Cr,17500.0,thane,779 sqft,Ready to Move,10 out of 29,Resale,...,East,Garden/Park,Sunrise by Kalpataru,2,NaN,1 Covered,Freehold,NaN,NaN,NaN

In [150]:
df.shape

(187531, 21)

In [151]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 187531 entries, 0 to 187530
Data columns (total 21 columns):
 #   Column             Non-Null Count   Dtype
---  ------             --------------   -----
 0   Index              187531 non-null  int64
 1   Title              187531 non-null  object
 2   Description        184508 non-null  object
 3   Amount(in rupees)  187531 non-null  object
 4   Price (in rupees)  169866 non-null  float64
 5   location           187531 non-null  object
 6   Carpet Area        106858 non-null  object
 7   Status             186916 non-null  object
 8   Floor              180454 non-null  object
 9   Transaction        187448 non-null  object
 10  Furnishing         184634 non-null  object
 11  facing             117298 non-null  object
 12  overlooking        106095 non-null  object
 13  Society            77853 non-null   object
 14  Bathroom           186703 non-null  object
 15  Balcony            138596 non-null  object
 16  Car Parking        84174 non-null   object
 17  Ownership          122014 non-null  object
 18  Super Area         79846 non-null   object
 19  Dimensions         0 non-null       float64
 20  Plot Area          0 non-null       float64
dtypes: float64(3), int64(1), object(17)
memory usage: 30.0+ MB

In [152]:
df.isnull().sum()

Index                     0
Title                     0
Description            3023
Amount(in rupees)         0
Price (in rupees)     17665
location                  0
Carpet Area           80673
Status                  615
Floor                  7077
Transaction              83
Furnishing             2897
facing                70233
overlooking           81436
Society              109678
Bathroom                828
Balcony               48935
Car Parking          103357
Ownership             65517
Super Area           107685
Dimensions           187531
Plot Area            187531
dtype: int64

In [153]:
df.duplicated().sum()

np.int64(0)

In [154]:
df.describe()

               Index  Price (in rupees)  Dimensions  Plot Area
count  187531.000000       1.698660e+05         0.0        0.0
mean    93765.000000       7.583772e+03         NaN        NaN
std     54135.681003       2.724171e+04         NaN        NaN
min         0.000000       0.000000e+00         NaN        NaN
25%     46882.500000       4.297000e+03         NaN        NaN
50%     93765.000000       6.034000e+03         NaN        NaN
75%    140647.500000       9.450000e+03         NaN        NaN
max    187530.000000       6.700000e+06         NaN        NaN

### EDA

In [155]:
# Modificacion de los datos
df_new = df.copy()

In [156]:
df_new.columns

Index(['Index', 'Title', 'Description', 'Amount(in rupees)',
       'Price (in rupees)', 'location', 'Carpet Area', 'Status', 'Floor',
       'Transaction', 'Furnishing', 'facing', 'overlooking', 'Society',
       'Bathroom', 'Balcony', 'Car Parking', 'Ownership', 'Super Area',
       'Dimensions', 'Plot Area'],
      dtype='object')

In [157]:
# Modifficar nombre de las columnas


df_new.rename(columns={
    'Index': 'indice',
    'Title': 'titulo',
    'Description': 'descripcion',
    'Amount(in rupees)': 'monto',
    'Price (in rupees)': 'precio',
    'location': 'ubicacion',
    'Carpet Area': 'area_util',
    'Status': 'estado',
    'Floor': 'piso',
    'Transaction': 'transaccion',
    'Furnishing': 'mobiliario',
    'facing': 'orientacion',
    'overlooking': 'vista',
    'Society': 'sociedad',
    'Bathroom': 'banos',
    'Balcony': 'balcones',
    'Car Parking': 'estacionamiento',
    'Ownership': 'propiedad',
    'Super Area': 'area_total',
    'Dimensions': 'dimensiones',
    'Plot Area': 'terreno'
}, inplace=True)

In [158]:
df_new["propiedad"].value_counts()

propiedad
Freehold                112229
Leasehold                 5285
Co-operative Society      3431
Power Of Attorney         1069
Name: count, dtype: int64

In [159]:
df_new.isnull().sum()

indice                  0
titulo                  0
descripcion          3023
monto                   0
precio              17665
ubicacion               0
area_util           80673
estado                615
piso                 7077
transaccion            83
mobiliario           2897
orientacion         70233
vista               81436
sociedad           109678
banos                 828
balcones            48935
estacionamiento    103357
propiedad           65517
area_total         107685
dimensiones        187531
terreno            187531
dtype: int64

In [160]:
df_new = df_new.drop(columns=["terreno", "dimensiones", "area_total","orientacion","transaccion","vista"])

In [161]:
df_new.head(3)

,indice,titulo,descripcion,monto,precio,ubicacion,area_util,estado,piso,mobiliario,sociedad,banos,balcones,estacionamiento,propiedad
0,0,1 BHK Ready to Occupy Flat for sale in Srushti...,"Bhiwandi, Thane has an attractive 1 BHK Flat f...",42 Lac,6000.0,thane,500 sqft,Ready to Move,10 out of 11,Unfurnished,Srushti Siddhi Mangal Murti Complex,1,2,NaN,NaN
1,1,2 BHK Ready to Occupy Flat for sale in Dosti V...,One can find this stunning 2 BHK flat for sale...,98 Lac,13799.0,thane,473 sqft,Ready to Move,3 out of 22,Semi-Furnished,Dosti Vihar,2,NaN,1 Open,Freehold
2,2,2 BHK Ready to Occupy Flat for sale in Sunrise...,Up for immediate sale is a 2 BHK apartment in ...,1.40 Cr,17500.0,thane,779 sqft,Ready to Move,10 out of 29,Unfurnished,Sunrise by Kalpataru,2,NaN,1 Covered,Freehold

In [162]:
# valores nulos

df_new.isnull().sum()

indice                  0
titulo                  0
descripcion          3023
monto                   0
precio              17665
ubicacion               0
area_util           80673
estado                615
piso                 7077
mobiliario           2897
sociedad           109678
banos                 828
balcones            48935
estacionamiento    103357
propiedad           65517
dtype: int64

In [163]:
df_new["descripcion"] = df_new["descripcion"].fillna("Sin descripcion")

In [164]:
print(f"porcentaje de valores nulos en precio: {df_new["precio"].isnull().sum() /len(df_new)*100:.2f}%")

porcentaje de valores nulos en precio: 9.42%

In [165]:
# imputacion de precio
df_new["precio"] = df_new["precio"]

In [166]:
df_new["precio"].fillna(df_new["precio"].mean(), inplace=True)

C:\Users\rqm\AppData\Local\Temp\ipykernel_25644\956640748.py:1: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  df_new["precio"].fillna(df_new["precio"].mean(), inplace=True)

In [167]:
df_new["area_util"] = df_new["area_util"].str.replace("sqft", "",regex= False) 
df_new["area_util"] = pd.to_numeric(df_new["area_util"], errors="coerce")

In [168]:
df_new["area_m2"] = df_new["area_util"] * 0.092903

df_new["area_m2"].head(3)

0    46.451500
1    43.943119
2    72.371437
Name: area_m2, dtype: float64

In [169]:
df_new["area_m2"] = df_new["area_m2"].fillna(
    df_new.groupby("titulo")["area_m2"]
    .transform("mean")
)

In [170]:
df_new["area_m2"].fillna(df_new["area_m2"].mean(), inplace=True)

C:\Users\rqm\AppData\Local\Temp\ipykernel_25644\3796608688.py:1: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  df_new["area_m2"].fillna(df_new["area_m2"].mean(), inplace=True)

In [171]:
df_new.drop(columns=["area_util","piso","sociedad","estacionamiento", "propiedad" ], inplace=True)

In [172]:
df_new["estado"].fillna("Desconocido", inplace=True)

C:\Users\rqm\AppData\Local\Temp\ipykernel_25644\1074078151.py:1: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  df_new["estado"].fillna("Desconocido", inplace=True)

In [176]:
df_new["mobiliario"].fillna("Desconocido", inplace=True)

In [181]:
df_new["banos"]= pd.to_numeric(df_new["banos"], errors="coerce")

In [182]:
df_new["banos"].fillna(df_new["banos"].median(), inplace=True)

C:\Users\rqm\AppData\Local\Temp\ipykernel_25644\2599034596.py:1: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  df_new["banos"].fillna(df_new["banos"].median(), inplace=True)

In [185]:
df_new["balcones"]= pd.to_numeric(df_new["balcones"], errors="coerce")

In [186]:
df_new["balcones"].fillna(df_new["balcones"].median(), inplace=True)

C:\Users\rqm\AppData\Local\Temp\ipykernel_25644\4232382522.py:1: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  df_new["balcones"].fillna(df_new["balcones"].median(), inplace=True)

In [187]:
df_new.isnull().sum()

indice         0
titulo         0
descripcion    0
monto          0
precio         0
ubicacion      0
estado         0
mobiliario     0
banos          0
balcones       0
area_m2        0
dtype: int64

In [189]:
df_new.head()

,indice,titulo,descripcion,monto,precio,ubicacion,estado,mobiliario,banos,balcones,area_m2
0,0,1 BHK Ready to Occupy Flat for sale in Srushti...,"Bhiwandi, Thane has an attractive 1 BHK Flat f...",42 Lac,6000.000000,thane,Ready to Move,Unfurnished,1.0,2.0,46.451500
1,1,2 BHK Ready to Occupy Flat for sale in Dosti V...,One can find this stunning 2 BHK flat for sale...,98 Lac,13799.000000,thane,Ready to Move,Semi-Furnished,2.0,2.0,43.943119
2,2,2 BHK Ready to Occupy Flat for sale in Sunrise...,Up for immediate sale is a 2 BHK apartment in ...,1.40 Cr,17500.000000,thane,Ready to Move,Unfurnished,2.0,2.0,72.371437
3,3,1 BHK Ready to Occupy Flat for sale Kasheli,This beautiful 1 BHK Flat is available for sal...,25 Lac,7583.771885,thane,Ready to Move,Unfurnished,1.0,1.0,49.238590
4,4,2 BHK Ready to Occupy Flat for sale in TenX Ha...,"This lovely 2 BHK Flat in Pokhran Road, Thane ...",1.60 Cr,18824.000000,thane,Ready to Move,Unfurnished,2.0,2.0,58.993405

# Regrecion Lineal

In [190]:
from sklearn.model_selection import train_test_split, cross_validate
from sklearn.preprocessing import StandardScaler
from sklearn.linear_model import LinearRegression
from sklearn.metrics import mean_absolute_error, mean_squared_error, r2_score